commit_message: '[skip ci] Update translations (%language%) %original_file_name%'
pull_request_title: 'i18n: update translations'
pull_request_labels:
  - i18n
files:
  - source: /en/**/*.md
    translation: /%locale_with_underscore%/**/%file_name%.md
  - source: /.vitepress/config/en.ts
    translation: /.vitepress/config/%locale_with_underscore%.ts